AllCops:
  Exclude:
    - 'db/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'bin/*'
    - 'Guardfile'
    - 'Rakefile'
    - 'lib/tasks/*'
    - 'lib/api_error_log.rb'

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact
