AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config/initializers/**/*'
    - 'config/environments/**/*'
    - 'config/application.rb'
    - 'config/routes.rb'
    - 'bin/*'
    - '**/Guardfile'
    - '**/Rakefile'
    - 'lib/tasks/**/*'
    - 'lib/api_error_log.rb'
    - '**/*.gemspec'
    - '**/Gemfile'
    - '**/i18n/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 15
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false
