language: ruby
rvm:
  - 2.3.1
env:
  - DB=postgresql
services:
  - postgresql
script:
  - RAILS_ENV=test bundle exec rake db:reset
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - bundle exec rspec
  - bundle exec rubocop
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
