sudo: required
dist: trusty

language: ruby

rvm:
  - 2.5.0

addons:
  postgresql: "9.5"
  firefox: "54.0"

before_script:
  - psql -c 'create database glownet_web_test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

bundler_args: --without production

cache: bundler

before_install:
  - "gem update --system"
  - "gem update bundler"
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.17.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

script:
  - RAILS_ENV=test bundle exec rake db:drop
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake stats:db:drop
  - RAILS_ENV=test bundle exec rake stats:db:create
  - RAILS_ENV=test bundle exec rake stats:db:migrate --trace
  - RAILS_ENV=test bundle exec rake stats:db:test:prepare
  - bundle exec rspec --fail-fast

matrix:
  fast_finish: true

