min_version_apk: "1.0"
private_zone_password: "123456"
fast_removal_password: "123456"
uid_reverse: false
touchpoint_update_online_orders: false
pos_update_online_orders: false
topup_initialize_gtag: true
cypher_enabled: false
gtag_blacklist: ""
transaction_buffer: 100
days_to_keep_backup: 5
days_to_keep_backup_min: 0
sync_time_event_parameters: 1
sync_time_event_parameters_min: 1
sync_time_server_date: 1
sync_time_server_date_min: 0
sync_time_basic_download: 5
sync_time_basic_download_min: 0
sync_time_tickets: 5
sync_time_tickets_min: 0
sync_time_gtags: 10
sync_time_gtags_min: 0
sync_time_customers: 10
sync_time_customers_min: 0
