maximum_gtag_balance: 300
gtag_type: ultralight_c
format: Standard
cards_can_refund: false
wristbands_can_refund: false
gtag_deposit: 0
ultralight_c:
  ultralight_c_private_key: <%= SecureRandom.hex(16) %>
ultralight_ev1:
  ultralight_ev1_private_key: <%= SecureRandom.hex(16) %>
mifare_classic:
  mifare_classic_public_key: <%= SecureRandom.hex(6) %>
  mifare_classic_private_key_a: <%= SecureRandom.hex(6) %>
  mifare_classic_private_key_b: <%= SecureRandom.hex(6) %>
