paypal:
  actions:
    - topup
    - refund
  config:
    - login
    - password
    - signature

vouchup:
  actions:
    - topup
    - refund
  host:
    development: "dev.wiredlion.io"
    sandbox: "demo.wiredlion.io"
    production: "wiredlion.io"
    test: "dev.wiredlion.io"
    
bank_account:
  actions:
    - refund
