commons: &commons
  actions:
    - topup

paypal:
  <<: *commons
  config:
    - login
    - password
    - signature

mercadopago:
  <<: *commons
  config:
    - public_key
    - token

redsys:
  <<: *commons
  config:
    - login
    - secret_key
    - terminal

stripe:
  <<: *commons
  config:
    - login
    - destination

wirecard:
  <<: *commons
  config:
    - client_id
    - client_secret

bank_account:
  actions:
    - refund
  refund:
    - fee
    - minimum
