commons: &commons
  actions:
    - topup

paypal:
  actions:
    - topup
    - refund
  config:
    - login
    - password
    - signature

mercadopago:
  actions:
    - topup
    - refund
  config:
    - public_key
    - token

redsys:
  <<: *commons
  config:
    - login
    - secret_key
    - terminal

stripe:
  <<: *commons
  config:
    - login
    - destination

bank_account:
  actions:
    - refund
