common: &common
  eventbrite_client_secret: <%= Figaro.env.eventbrite_client_secret %>
  eventbrite_client_id: <%= Figaro.env.eventbrite_client_id %>
  eventbrite_auth_url: https://www.eventbrite.com/oauth/authorize

  universe_client_id: <%= Figaro.env.universe_client_id %>
  universe_client_secret: <%= Figaro.env.universe_client_secret %>
  universe_webhooks_secret: <%= Figaro.env.universe_webhooks_secret %>

  universe_app_url: https://glownet.ngrok.io/admins/universe/auth
  universe_auth_url: https://www.universe.com/oauth/authorize
  universe_token_url: https://www.universe.com/oauth/token
  universe_user_url: https://www.universe.com/api/v2/current_user
  universe_listings_url: https://www.universe.com/api/v2/listings
  universe_barcodes_url: https://www.universe.com/api/v2/guestlists

  stubhub_auth_url: https://test.palco4.com/accessControlApi/users/login
  stubhub_venues_url: https://test.palco4.com/accessControlApi/sessions/info/json
  stubhub_barcodes_url: https://test.palco4.com/accessControlApi/barcodes/getListFromActiveSessions/json

  qwantiq_auth_url: https://test.palco4.com/accessControlApi/users/login
  qwantiq_venues_url: https://test.palco4.com/accessControlApi/sessions/info/json
  qwantiq_barcodes_url: https://test.palco4.com/accessControlApi/barcodes/getListFromActiveSessions/json

development:
  <<: *common

test:
  <<: *common

integration:
  <<: *common
  universe_app_url: https://integration.glownet.com/admins/universe/auth

sandbox:
  <<: *common
  universe_app_url: https://sandbox.glownet.com/admins/universe/auth

  stubhub_auth_url: https://eur.stubhubtickets.com/accessControlApi/users/login
  stubhub_venues_url: https://eur.stubhubtickets.com/accessControlApi/sessions/info/json
  stubhub_barcodes_url: https://eur.stubhubtickets.com/accessControlApi/barcodes/getListFromActiveSessions/json

  qwantiq_auth_url: https://www.entradas.plus/accessControlApi/users/login
  qwantiq_venues_url: https://www.entradas.plus/accessControlApi/sessions/info/json
  qwantiq_barcodes_url: https://www.entradas.plus/accessControlApi/barcodes/getListFromActiveSessions/json

staging:
  <<: *common
  universe_app_url: https://staging.glownet.com/admins/universe/auth

production:
  <<: *common
  universe_app_url: https://gspot.glownet.com/admins/universe/auth

  stubhub_auth_url: https://eur.stubhubtickets.com/accessControlApi/users/login
  stubhub_venues_url: https://eur.stubhubtickets.com/accessControlApi/sessions/info/json
  stubhub_barcodes_url: https://eur.stubhubtickets.com/accessControlApi/barcodes/getListFromActiveSessions/json

  qwantiq_auth_url: https://www.entradas.plus/accessControlApi/users/login
  qwantiq_venues_url: https://www.entradas.plus/accessControlApi/sessions/info/json
  qwantiq_barcodes_url: https://www.entradas.plus/accessControlApi/barcodes/getListFromActiveSessions/json
