common: &common
  eventbrite_client_secret: <%= Figaro.env.eventbrite_client_secret %>
  eventbrite_client_id: <%= Figaro.env.eventbrite_client_id %>
  eventbrite_auth_url: https://www.eventbrite.com/oauth/authorize

  universe_client_id: <%= Figaro.env.universe_client_id %>
  universe_client_secret: <%= Figaro.env.universe_client_secret %>
  universe_webhooks_secret: <%= Figaro.env.universe_webhooks_secret %>

  universe_app_url: https://glownet.ngrok.io/admins/universe/auth
  universe_auth_url: https://www.universe.com/oauth/authorize
  universe_token_url: https://www.universe.com/oauth/token
  universe_user_url: https://www.universe.com/api/v2/current_user
  universe_listings_url: https://www.universe.com/api/v2/listings
  universe_barcodes_url: https://www.universe.com/api/v2/guestlists

  stubhub_auth_url: https://eur.stubhubtickets.com/accessControlApi/users/login
  stubhub_venues_url: https://eur.stubhubtickets.com/accessControlApi/sessions/info/json
  stubhub_barcodes_url: https://eur.stubhubtickets.com/accessControlApi/barcodes/getListFromActiveSessions/json

  qwantiq_auth_url: https://www.entradas.plus/accessControlApi/users/login
  qwantiq_venues_url: https://www.entradas.plus/accessControlApi/sessions/info/json
  qwantiq_barcodes_url: https://www.entradas.plus/accessControlApi/barcodes/getListFromActiveSessions/json
  
  ticketmaster_url_1: http://glowtm.ddns.net/TicketingServices_ES/formatedService.php
  ticket_master_params:
    header:
      ver: 1
      sid: SYSTEMCALL
      bid: SYSTEMCALL
      cip: 1.2.3.4
      token: 0
      mode: 0
    command1: 
      cmd: AccessControl.getEntryCodes
      reference: 0
      cmd_header:
        cmd_ver: 1_0_0_0
        lang_code: es
        market: ES
      extended_response_format: 0

development:
  <<: *common
  ticket_master_event: 
test:
  <<: *common

integration:
  <<: *common
  universe_app_url: https://integration.glownet.com/admins/universe/auth

sandbox:
  <<: *common
  universe_app_url: https://sandbox.glownet.com/admins/universe/auth
  ticket_master_event: 200

staging:
  <<: *common
  universe_app_url: https://staging.glownet.com/admins/universe/auth

production:
  <<: *common
  universe_app_url: https://gspot.glownet.com/admins/universe/auth
  ticket_master_event: 428
