default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: gspot_dev

test:
  <<: *default
  database: gspot_test

staging:
  <<: *default
  database: gspot_staging

production:
  <<: *default
  database: gspot
  username: gspot
  password: ConTango0912
  pool: 10