default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  port: 5432
  host: <%= ENV["POSTGRES_HOST"] || ENV["pg_host"] %>
  username: <%= ENV["POSTGRES_USERNAME"] || ENV["pg_username"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] || ENV["pg_password"] %>

development:
  <<: *default
  pool: 10
  database: cloud_development

test:
  <<: *default
  database: cloud_test

demo:
  <<: *default
  database: cloud_demo

integration:
  <<: *default
  database: cloud_integration

sandbox:
  <<: *default
  database: cloud_sandbox

staging:
  <<: *default
  database: cloud_staging

hotfix:
  <<: *default
  pool: 15
  database: cloud_hotfix

production:
  <<: *default
  database: cloud_production
  pool: 10
