default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  port: 5432
  host: glownethotfixdb.c1k2l4qxgc40.eu-west-1.rds.amazonaws.com
  password: <%= ENV["POSTGRES_PASSWORD"] || ENV["pg_password"] %>

development:
  <<: *default
  pool: 10
  database: glownet_web_development
  username: <%= ENV["POSTGRES_USER"] || ENV["pg_username"] %>
  host: <%= ENV["POSTGRES_HOST"] || ENV["pg_host"] %>

test:
  <<: *default
  database: glownet_web_test
  username: <%= ENV["POSTGRES_USER"] || ENV["pg_username"] %>
  host: <%= ENV["POSTGRES_HOST"] || ENV["pg_host"] %>

demo:
  <<: *default
  database: glownet_web_demo
  username: glownet

integration:
  <<: *default
  database: glownet_web_integration
  username: glownet

sandbox:
  <<: *default
  database: glownet_web_sandbox
  username: glownet

staging:
  <<: *default
  database: glownet_web_staging
  username: glownet

hotfix:
  <<: *default
  pool: 15
  database: glownet_web_hotfix
  username: glownet

production:
  <<: *default
  database: cloud_production
  username: glowballMaster
  host: glownet-production.c1k2l4qxgc40.eu-west-1.rds.amazonaws.com
  pool: 10
