scss_files: 'apps/customer_area/app/assets/stylesheets'

exclude:
  - '../apps/customer_area/app/assets/stylesheets/vendor/*.*'
  - '../apps/customer_area/app/assets/stylesheets/lib/**/*.*'
  - '../apps/customer_area/app/assets/stylesheets/glownet/customer/configuration/*.*'
  - '../apps/customer_area/app/assets/stylesheets/glownet/customer/_template_variables.scss'
linters:
  BorderZero:
    enabled: true
    convention: none
  ColorVariable:
    enabled: true
  Comment:
    enabled: true
    style: silent
  DuplicateProperty:
    enabled: true
  ExtendDirective:
    enabled: true
  IdSelector:
    enabled: true
  LeadingZero:
    enabled: true
    style: include_zero
  MergeableSelector:
    enabled: true
    force_nesting: true
  NameFormat:
    enabled: false
    allow_leading_underscore: true
    convention: snake_case
  NestingDepth:
    enabled: true
    max_depth: 3
    ignore_parent_selectors: false
  PropertySortOrder:
    #enabled: false
    order:
      - clear
      - position
      - top
      - right
      - bottom
      - left
      - z-index
      - display
      - float
      - vertical-align
      - overflow
      - width
      - height
      - margin
      - padding
      - border
      - box-shadow
      - background
      - background-color
      - color
      - font-family
      - font-size
      - line-height
      - text-align
      - white-space
      - text-overflow
      - opacity
      - cursor
    ignore_unspecified: true
    separate_groups: false
  PseudoElement:
    enabled: false
  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: false
    allow_element_with_id: false
  SingleLinePerSelector:
    enabled: true
  StringQuotes:
    enabled: true
    style: double_quotes
  TransitionAll:
    enabled: true
  ZeroUnit:
    enabled: true
