common: &common
  secret_key_base: <%= Figaro.env.secret_key_base %>
  host: 'localhost:3000'
  host_url: 'http://localhost:3000/'

  devise_secret_key: <%= Figaro.env.devise_secret_key %>
  devise_mail_sender: 'no-reply@glownet.com'

  google_analytics: UA-63172076-1

  recaptcha_site_key: <%= Figaro.env.recaptcha_site_key %>
  recaptcha_secret_key: <%= Figaro.env.recaptcha_secret_key %>

  facebook_public: <%= Figaro.env.facebook_public %>
  facebook_secret: <%= Figaro.env.facebook_secret %>

  google_public: <%= Figaro.env.google_public %>
  google_secret: <%= Figaro.env.google_secret %>

  smtp_username: 'online@glownet.com'
  smtp_password: <%= Figaro.env.smtp_password %>

  s3_access_key_id: <%= Figaro.env.s3_access_key_id %>
  s3_secret_access_key: <%= Figaro.env.s3_secret_access_key %>
  s3_bucket: gspot-development
  s3_images_folder: gspot
  s3_region: s3-eu-west-1
  s3_hostname: s3-eu-west-1.amazonaws.com

  ticket_config_1: <%= Figaro.env.ticket_config_1 %>
  wiredlion_host: "dev.wiredlion.io"

development:
  <<: *common
  redis_server: redis://localhost:6379/0
  redis_client: redis://localhost:6379/0

test:
  <<: *common
  secret_key_base: 7d7e178a46197575fb16e05acd5e98572fc4426dfbd9dbc6d8bd645d059550f68b26cf910df85a22edb7946f17067fde6386c4e92b724ec9aabf30c00b506359

integration:
  <<: *common
  s3_bucket: gspot-integration
  host: 'integration.glownet.com'
  host_url: 'https://integration.glownet.com'

sandbox:
  <<: *common
  s3_bucket: gspot-sandbox
  host: 'sandbox.glownet.com'
  host_url: 'https://sandbox.glownet.com'
  wiredlion_host: "demo.wiredlion.io"

staging:
  <<: *common
  s3_bucket: gspot-staging
  host: 'staging.glownet.com'
  host_url: 'https://staging.glownet.com'

production:
  <<: *common
  ticket_config_1: <%= ENV["ticket_config_1"] %>
  google_analytics: UA-63172076-2
  s3_bucket: gspot-production
  host: 'gspot.glownet.com'
  host_url: 'https://gspot.glownet.com'
  secret_key_base: <%= ENV["secret_key_base"] %>
  wiredlion_host: "wiredlion.io"
