common: &common
  secret_key_base: <%= Figaro.env.secret_key_base %>
  host: 'localhost:3000'
  host_url: 'http://localhost:3000/'

  devise_secret_key: <%= Figaro.env.devise_secret_key %>
  devise_mail_sender: 'no-reply@glownet.com'
  from_email: 'Glownet <no-reply@glownet.com>'

  google_analytics: UA-63172076-1

  recaptcha_public_key: <%= Figaro.env.recaptcha_public_key %>
  recaptcha_private_key: <%= Figaro.env.recaptcha_private_key %>

  facebook_public: <%= Figaro.env.facebook_public %>
  facebook_secret: <%= Figaro.env.facebook_secret %>

  google_public: <%= Figaro.env.google_public %>
  google_secret: <%= Figaro.env.google_secret %>

  smtp_address: 'smtp.mandrillapp.com'
  smtp_port: '587'
  smtp_domain: 'smtp.mandrillapp.com'
  smtp_username: 'online@glownet.com'
  smtp_password: <%= Figaro.env.smtp_password %>
  smtp_authentication: 'plain'
  smtp_enable_starttls_auto: 'true'
  smtp_openssl_verify_mode: 'none'

  s3_access_key_id: <%= Figaro.env.s3_access_key_id %>
  s3_secret_access_key: <%= Figaro.env.s3_secret_access_key %>
  s3_bucket: gspot-development
  s3_images_folder: gspot
  s3_region: s3-eu-west-1
  s3_hostname: s3-eu-west-1.amazonaws.com

  redis_server: redis://localhost:6379
  redis_client: redis://localhost:6379

  stripe_platform_secret: <%= Figaro.env.stripe_platform_secret %>
  stripe_platform_publishable: <%= Figaro.env.stripe_platform_publishable %>

  ticket_config_1: <%= Figaro.env.ticket_config_1 %>

development:
  <<: *common
  redis_server: redis://localhost:6379/0
  redis_client: redis://localhost:6379/0

test:
  <<: *common

demo:
  <<: *common
  s3_bucket: gspot-demo
  host: 'demo.glownet.com'
  host_url: 'https://demo.glownet.com'

integration:
  <<: *common
  s3_bucket: gspot-integration
  host: 'integration.glownet.com'
  host_url: 'https://integration.glownet.com'

sandbox:
  <<: *common
  s3_bucket: gspot-sandbox
  host: 'sandbox.glownet.com'
  host_url: 'https://sandbox.glownet.com'

staging:
  <<: *common
  s3_bucket: gspot-staging
  host: 'staging.glownet.com'
  host_url: 'https://staging.glownet.com'

production:
  <<: *common
  ticket_config_1: <%= ENV["ticket_config_1"] %>
  stripe_platform_secret: <%= ENV["stripe_platform_secret"] %>
  stripe_platform_publishable: <%= ENV["stripe_platform_publishable"] %>
  google_analytics: UA-63172076-2
  s3_bucket: gspot-production
  host: 'gspot.glownet.com'
  host_url: 'https://gspot.glownet.com'
  secret_key_base: <%= ENV["secret_key_base"] %>

hotfix:
  <<: *common
  s3_bucket: gspot-hotfix
  host: 'hotfix.glownet.com'
  host_url: 'https://hotfix.glownet.com'
  secret_key_base: <%= ENV["secret_key_base"] %>
