# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
common: &common
  devise_secret_key: '309f306006453056bdae31abc4a4a808f58d4b53082b141f4419edd67c22dc37b12a9522c513e29e119b12de09744b4e659876a01fabd51a4e23391f49b94f01'
  devise_pepper: 'b337316a4cecbfb5819d571a4044e4b907669763225e339b1e48b45de4a1f1c62a99cc7f544caa477e892ab38faabb15b6e222edbbacb6616a1fcd77816ecf6c'
  mail_host: 'localhost'
  devise_mail_sender: 'no-reply@glownet.com'
  smtp_server: 'smtp.gmail.com'
  smtp_url: 'acidtango.com'
  mail_username: 'admin@acidtango.com'
  mail_password: 'acido9823'
  domain_url: 'localhost'

development:
  <<: *common
  secret_key_base: 705edc18cbe323507eab47c93c15c4810a68d8d8604f228e77923191a580f93e50354a2b7c481272091d6f06169a18d3c58abcfb5de317311a35506ea73e9146

test:
  <<: *common
  secret_key_base: e4c8d127839bbc3fcd529244e8ece3fa81cedad487431fdd12f3761c1949feef7e33c7b5ccc424d6bc1c56594523a4a07198522f776542dddc356fbb109d680d
  domain_url: 'localhost'

staging:
  <<: *common
  secret_key_base: 705edc18cbe323507eab47c93c15c4810a68d8d8604f228e77923191a580f93e50354a2b7c481272091d6f06169a18d3c58abcfb5de317311a35506ea73e9146
  domain_url: 'localhost'

production:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_url: 'localhost'

