---
# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
:verbose: false
:concurrency: 2
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 15

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - default
  - medium
  - medium_low
  - low

# you can override settings based on environment
production:
  :concurrency: 2

development:
  :concurrency: 10
